import jsPDF from "jspdf";

export default function generateQuotePDF(quote) {
  const pdf = new jsPDF();

  pdf.setFontSize(20);
  pdf.text("C & D Shipping", 20, 20);

  pdf.setFontSize(12);
  pdf.text("Quote Reference: " + quote.id, 20, 35);
  pdf.text("Customer: " + quote.customerName, 20, 45);
  pdf.text("Country: " + quote.country, 20, 55);
  pdf.text("Status: " + quote.status, 20, 65);

  pdf.line(20, 72, 190, 72);

  pdf.text("Goods Value:", 20, 85);
  pdf.text(String(quote.value || 0), 150, 85);

  pdf.text("Duty:", 20, 95);
  pdf.text(String(Number(quote.duty || 0).toFixed(2)), 150, 95);

  pdf.text("Clearance:", 20, 105);
  pdf.text(String(Number(quote.clearance || 0).toFixed(2)), 150, 105);

  pdf.text("Delivery:", 20, 115);
  pdf.text(String(Number(quote.delivery || 0).toFixed(2)), 150, 115);

  pdf.line(20, 125, 190, 125);

  pdf.setFontSize(16);
  pdf.text(
    "TOTAL: " +
      quote.currency +
      " " +
      Number(quote.total || 0).toFixed(2),
    20,
    140
  );

  pdf.setFontSize(10);
  pdf.text(
    "Generated by C & D Admin Platform",
    20,
    280
  );

  pdf.save("Quote-" + quote.id + ".pdf");
}
